[package]
name = "kata-agent-fuzz"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
kata-agent = { path = ".." }
libfuzzer-sys = { version = "0.4", features = ["arbitrary-derive"] }
arbitrary = "1.4.1"
protobuf = "3.2.0"
protocols = { path = "../../libs/protocols", features = ["async", "with-serde"] }
tokio = { version = "1.39.0", features = ["full"] }
ttrpc = { version = "0.8.4", features = ["async"], default-features = false }
lazy_static = "1.3.0"
rand = "0.8.4"
anyhow = "1.0.31"

# Image pull/unpack
image-rs = { git = "https://github.com/confidential-containers/guest-components", rev = "v0.10.0", features = ["snapshot-overlayfs", "oci-client-rustls", "signature-cosign-rustls"] }

safe-path = { path = "../../libs/safe-path" }

[workspace]
members = ["."]

[[bin]]
name = "random"
path = "fuzz_targets/random.rs"
test = false
doc = false
bench = false

[[bin]]
name = "exec_process"
path = "fuzz_targets/exec_process.rs"
test = false
doc = false
bench = false
